const response = {
  "href": "https://api.spotify.com/v1/playlists/37jxc8QYZQ784rm2GZVXpF/tracks?offset=0&limit=100",
  "items": [
    {
      "added_at": "2018-10-10T21:00:43Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/57vWImR43h4CaDao012Ofp"
              },
              "href": "https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp",
              "id": "57vWImR43h4CaDao012Ofp",
              "name": "Steve Lacy",
              "type": "artist",
              "uri": "spotify:artist:57vWImR43h4CaDao012Ofp"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5fvUFzgVEni3L7769OabqQ"
          },
          "href": "https://api.spotify.com/v1/albums/5fvUFzgVEni3L7769OabqQ",
          "id": "5fvUFzgVEni3L7769OabqQ",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/86bdcf70225bff88668258977d0119bc7ddc2008",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/f75094ad12bddb79ec31d8792f17544e496c802b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ad818ef1c66f26e227faf53ea2ccd089883a1920",
              "width": 64
            }
          ],
          "name": "Dark Red",
          "release_date": "2017-02-20",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:5fvUFzgVEni3L7769OabqQ"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/57vWImR43h4CaDao012Ofp"
            },
            "href": "https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp",
            "id": "57vWImR43h4CaDao012Ofp",
            "name": "Steve Lacy",
            "type": "artist",
            "uri": "spotify:artist:57vWImR43h4CaDao012Ofp"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 173104,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "GBKPL1778015"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/37y7iDayfwm3WXn5BiAoRk"
        },
        "href": "https://api.spotify.com/v1/tracks/37y7iDayfwm3WXn5BiAoRk",
        "id": "37y7iDayfwm3WXn5BiAoRk",
        "is_local": false,
        "name": "Dark Red",
        "popularity": 68,
        "preview_url": "https://p.scdn.co/mp3-preview/8e9689ea710036af15eecca65f7ffe2720d2edab?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:37y7iDayfwm3WXn5BiAoRk"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-11-02T19:36:23Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6"
              },
              "href": "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
              "id": "066X20Nz7iquqkkCW6Jxy6",
              "name": "LCD Soundsystem",
              "type": "artist",
              "uri": "spotify:artist:066X20Nz7iquqkkCW6Jxy6"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/75bOa6MJhVgz1uzcZBUNhf"
          },
          "href": "https://api.spotify.com/v1/albums/75bOa6MJhVgz1uzcZBUNhf",
          "id": "75bOa6MJhVgz1uzcZBUNhf",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/fac2ce840c05f1ebb56f9360ffeee5f057cbf7d9",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/38535733505d41f411ac689a0e2bf9ec71f5b62c",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/fe256fa38db8d71f99e1166e3616e7274a7fac07",
              "width": 64
            }
          ],
          "name": "Spotify Singles",
          "release_date": "2018-09-12",
          "release_date_precision": "day",
          "total_tracks": 2,
          "type": "album",
          "uri": "spotify:album:75bOa6MJhVgz1uzcZBUNhf"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6"
            },
            "href": "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
            "id": "066X20Nz7iquqkkCW6Jxy6",
            "name": "LCD Soundsystem",
            "type": "artist",
            "uri": "spotify:artist:066X20Nz7iquqkkCW6Jxy6"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 344666,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM11806757"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5hSTBY6xBkx60qPVseOKFX"
        },
        "href": "https://api.spotify.com/v1/tracks/5hSTBY6xBkx60qPVseOKFX",
        "id": "5hSTBY6xBkx60qPVseOKFX",
        "is_local": false,
        "name": "tonite - Recorded at Electric Lady Studios NYC",
        "popularity": 44,
        "preview_url": "https://p.scdn.co/mp3-preview/65e9ffac64bed334041e83659992195dc8345109?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:5hSTBY6xBkx60qPVseOKFX"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-11-02T19:36:23Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6"
              },
              "href": "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
              "id": "066X20Nz7iquqkkCW6Jxy6",
              "name": "LCD Soundsystem",
              "type": "artist",
              "uri": "spotify:artist:066X20Nz7iquqkkCW6Jxy6"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/75bOa6MJhVgz1uzcZBUNhf"
          },
          "href": "https://api.spotify.com/v1/albums/75bOa6MJhVgz1uzcZBUNhf",
          "id": "75bOa6MJhVgz1uzcZBUNhf",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/fac2ce840c05f1ebb56f9360ffeee5f057cbf7d9",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/38535733505d41f411ac689a0e2bf9ec71f5b62c",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/fe256fa38db8d71f99e1166e3616e7274a7fac07",
              "width": 64
            }
          ],
          "name": "Spotify Singles",
          "release_date": "2018-09-12",
          "release_date_precision": "day",
          "total_tracks": 2,
          "type": "album",
          "uri": "spotify:album:75bOa6MJhVgz1uzcZBUNhf"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/066X20Nz7iquqkkCW6Jxy6"
            },
            "href": "https://api.spotify.com/v1/artists/066X20Nz7iquqkkCW6Jxy6",
            "id": "066X20Nz7iquqkkCW6Jxy6",
            "name": "LCD Soundsystem",
            "type": "artist",
            "uri": "spotify:artist:066X20Nz7iquqkkCW6Jxy6"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 622000,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM11806921"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0Abdq8INymRlkYbgM9QnGe"
        },
        "href": "https://api.spotify.com/v1/tracks/0Abdq8INymRlkYbgM9QnGe",
        "id": "0Abdq8INymRlkYbgM9QnGe",
        "is_local": false,
        "name": "home/i want your love - Recorded at Electric Lady Studios NYC",
        "popularity": 37,
        "preview_url": "https://p.scdn.co/mp3-preview/0be2fc2942ddcc279d4ae231925827cc1a07f43c?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:0Abdq8INymRlkYbgM9QnGe"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-11-02T19:36:49Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2qT62DYO8Ajb276vUJmvhz"
              },
              "href": "https://api.spotify.com/v1/artists/2qT62DYO8Ajb276vUJmvhz",
              "id": "2qT62DYO8Ajb276vUJmvhz",
              "name": "XTC",
              "type": "artist",
              "uri": "spotify:artist:2qT62DYO8Ajb276vUJmvhz"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4S6y2iTYbGONSlNJHYyrVl"
          },
          "href": "https://api.spotify.com/v1/albums/4S6y2iTYbGONSlNJHYyrVl",
          "id": "4S6y2iTYbGONSlNJHYyrVl",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/3d172170e7083d77b9aeb9bf644767fd1fcda5d5",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/7b31080852706dfcd744126c19d165d4916f7351",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/90dc0d2258fb116aa92e1e75f8cddda33b8f7aa7",
              "width": 64
            }
          ],
          "name": "Drums And Wires",
          "release_date": "1979-08-17",
          "release_date_precision": "day",
          "total_tracks": 15,
          "type": "album",
          "uri": "spotify:album:4S6y2iTYbGONSlNJHYyrVl"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2qT62DYO8Ajb276vUJmvhz"
            },
            "href": "https://api.spotify.com/v1/artists/2qT62DYO8Ajb276vUJmvhz",
            "id": "2qT62DYO8Ajb276vUJmvhz",
            "name": "XTC",
            "type": "artist",
            "uri": "spotify:artist:2qT62DYO8Ajb276vUJmvhz"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 202240,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "GBAAA0001011"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0pG73CkloiWrsiQlSYJDj8"
        },
        "href": "https://api.spotify.com/v1/tracks/0pG73CkloiWrsiQlSYJDj8",
        "id": "0pG73CkloiWrsiQlSYJDj8",
        "is_local": false,
        "name": "When You're Near Me I Have Difficulty - 2001 Digital Remaster",
        "popularity": 44,
        "preview_url": "https://p.scdn.co/mp3-preview/89de3b9fe546700f3e5cd74daceb18ff231a98a2?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:0pG73CkloiWrsiQlSYJDj8"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-11-06T16:36:15Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3inCNiUr4R6XQ3W43s9Aqi"
              },
              "href": "https://api.spotify.com/v1/artists/3inCNiUr4R6XQ3W43s9Aqi",
              "id": "3inCNiUr4R6XQ3W43s9Aqi",
              "name": "Pavement",
              "type": "artist",
              "uri": "spotify:artist:3inCNiUr4R6XQ3W43s9Aqi"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7Lv4eRt1QlaZXzxx5s2vvw"
          },
          "href": "https://api.spotify.com/v1/albums/7Lv4eRt1QlaZXzxx5s2vvw",
          "id": "7Lv4eRt1QlaZXzxx5s2vvw",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/e120c1838bbe2b414184b86b05d32258d32dfefa",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/9f2c401e6f89e7a600082e380774f288aec1a1ea",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/7d26aab261c4ffd9df998788043ea7ae2d547501",
              "width": 64
            }
          ],
          "name": "Brighten The Corners: Nicene Creedence Ed.",
          "release_date": "1997",
          "release_date_precision": "year",
          "total_tracks": 44,
          "type": "album",
          "uri": "spotify:album:7Lv4eRt1QlaZXzxx5s2vvw"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3inCNiUr4R6XQ3W43s9Aqi"
            },
            "href": "https://api.spotify.com/v1/artists/3inCNiUr4R6XQ3W43s9Aqi",
            "id": "3inCNiUr4R6XQ3W43s9Aqi",
            "name": "Pavement",
            "type": "artist",
            "uri": "spotify:artist:3inCNiUr4R6XQ3W43s9Aqi"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 206946,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USMTD0880519"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4tggZyGJMNJMooWuRbvN5q"
        },
        "href": "https://api.spotify.com/v1/tracks/4tggZyGJMNJMooWuRbvN5q",
        "id": "4tggZyGJMNJMooWuRbvN5q",
        "is_local": false,
        "name": "Harness Your Hopes - b-side",
        "popularity": 60,
        "preview_url": "https://p.scdn.co/mp3-preview/625ed756376ec64120806af0e0ca4988d5408547?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 19,
        "type": "track",
        "uri": "spotify:track:4tggZyGJMNJMooWuRbvN5q"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-11-25T23:44:12Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
              },
              "href": "https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
              "id": "3jK9MiCrA42lLAdMGUZpwa",
              "name": "Anderson .Paak",
              "type": "artist",
              "uri": "spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/3rqqwtJE89WoWvMyPTvbZc"
          },
          "href": "https://api.spotify.com/v1/albums/3rqqwtJE89WoWvMyPTvbZc",
          "id": "3rqqwtJE89WoWvMyPTvbZc",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/9cafc6cd0162e4926d84f21fffcbb56bc4d681ec",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/5a0feb7fa3449fcea3f956feff2c78784424989f",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/159d636567540df3d050bd2e13cb97b19237ea4e",
              "width": 64
            }
          ],
          "name": "Oxnard",
          "release_date": "2018-11-16",
          "release_date_precision": "day",
          "total_tracks": 14,
          "type": "album",
          "uri": "spotify:album:3rqqwtJE89WoWvMyPTvbZc"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
            },
            "href": "https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
            "id": "3jK9MiCrA42lLAdMGUZpwa",
            "name": "Anderson .Paak",
            "type": "artist",
            "uri": "spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 282986,
        "episode": false,
        "explicit": true,
        "external_ids": {
          "isrc": "ZZOPM1800713"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/0lG7iyNSstVOLV6faMIHdD"
        },
        "href": "https://api.spotify.com/v1/tracks/0lG7iyNSstVOLV6faMIHdD",
        "id": "0lG7iyNSstVOLV6faMIHdD",
        "is_local": false,
        "name": "6 Summers",
        "popularity": 67,
        "preview_url": "https://p.scdn.co/mp3-preview/12a42675483acadb3005f3cfc1b5c6e28fac67cb?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 5,
        "type": "track",
        "uri": "spotify:track:0lG7iyNSstVOLV6faMIHdD"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-12-03T17:56:33Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7yk35uHNQclPXFGFoTU44w"
              },
              "href": "https://api.spotify.com/v1/artists/7yk35uHNQclPXFGFoTU44w",
              "id": "7yk35uHNQclPXFGFoTU44w",
              "name": "The Pharcyde",
              "type": "artist",
              "uri": "spotify:artist:7yk35uHNQclPXFGFoTU44w"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/48kU5gP41TqZEw32Cwhsna"
          },
          "href": "https://api.spotify.com/v1/albums/48kU5gP41TqZEw32Cwhsna",
          "id": "48kU5gP41TqZEw32Cwhsna",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/75ed4e6fd0aae5f1b1112bb5e72ef9fe619a0b96",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/be6c3d76ae182047d592e91a75b4cc6fd3c7c94b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/9ec9750a01985d37c780e9122bd319b2b60c9867",
              "width": 64
            }
          ],
          "name": "Bizarre Ride II The Pharcyde",
          "release_date": "1992-11-24",
          "release_date_precision": "day",
          "total_tracks": 16,
          "type": "album",
          "uri": "spotify:album:48kU5gP41TqZEw32Cwhsna"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7yk35uHNQclPXFGFoTU44w"
            },
            "href": "https://api.spotify.com/v1/artists/7yk35uHNQclPXFGFoTU44w",
            "id": "7yk35uHNQclPXFGFoTU44w",
            "name": "The Pharcyde",
            "type": "artist",
            "uri": "spotify:artist:7yk35uHNQclPXFGFoTU44w"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 303493,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USA370513625"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/4G3dZN9o3o2X4VKwt4CLts"
        },
        "href": "https://api.spotify.com/v1/tracks/4G3dZN9o3o2X4VKwt4CLts",
        "id": "4G3dZN9o3o2X4VKwt4CLts",
        "is_local": false,
        "name": "Passin' Me By",
        "popularity": 67,
        "preview_url": "https://p.scdn.co/mp3-preview/2b5f082c10bc7cf228bbfb2f683f29e3815351e0?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 12,
        "type": "track",
        "uri": "spotify:track:4G3dZN9o3o2X4VKwt4CLts"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-12-06T07:54:29Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1tho5dJnzdYD57EQkM3SmK"
              },
              "href": "https://api.spotify.com/v1/artists/1tho5dJnzdYD57EQkM3SmK",
              "id": "1tho5dJnzdYD57EQkM3SmK",
              "name": "Chastity Belt",
              "type": "artist",
              "uri": "spotify:artist:1tho5dJnzdYD57EQkM3SmK"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5psuEv9OT8vMrW9TOiCGVS"
          },
          "href": "https://api.spotify.com/v1/albums/5psuEv9OT8vMrW9TOiCGVS",
          "id": "5psuEv9OT8vMrW9TOiCGVS",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/6c0ec40dea529765c2e35e5e9dbf9cb7a00163e9",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/bc0cc5023964842bb873e52c481f1bc44891e597",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/3586fa2105915fc85f28d30b7584fee9ef3e3f91",
              "width": 64
            }
          ],
          "name": "No Regerts",
          "release_date": "2013-08-13",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:5psuEv9OT8vMrW9TOiCGVS"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1tho5dJnzdYD57EQkM3SmK"
            },
            "href": "https://api.spotify.com/v1/artists/1tho5dJnzdYD57EQkM3SmK",
            "id": "1tho5dJnzdYD57EQkM3SmK",
            "name": "Chastity Belt",
            "type": "artist",
            "uri": "spotify:artist:1tho5dJnzdYD57EQkM3SmK"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 210508,
        "episode": false,
        "explicit": true,
        "external_ids": {
          "isrc": "ushm91311204"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/33fETuiMCbWEmAQGJmlx6S"
        },
        "href": "https://api.spotify.com/v1/tracks/33fETuiMCbWEmAQGJmlx6S",
        "id": "33fETuiMCbWEmAQGJmlx6S",
        "is_local": false,
        "name": "Pussy Weed Beer",
        "popularity": 34,
        "preview_url": "https://p.scdn.co/mp3-preview/4d4836c53fd50688b11b411e8868dccc37577119?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 9,
        "type": "track",
        "uri": "spotify:track:33fETuiMCbWEmAQGJmlx6S"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2018-12-06T07:54:34Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7jefIIksOi1EazgRTfW2Pk"
              },
              "href": "https://api.spotify.com/v1/artists/7jefIIksOi1EazgRTfW2Pk",
              "id": "7jefIIksOi1EazgRTfW2Pk",
              "name": "Electric Light Orchestra",
              "type": "artist",
              "uri": "spotify:artist:7jefIIksOi1EazgRTfW2Pk"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/3usnShwygMXVZB4IV5dwnU"
          },
          "href": "https://api.spotify.com/v1/albums/3usnShwygMXVZB4IV5dwnU",
          "id": "3usnShwygMXVZB4IV5dwnU",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/6e4bfaca5c09f0f480a51ac3b851e411b7338eb2",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/111a5fa4e18f5c46a027eec783c58aeccf0f8055",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/f5e5f35d1444cf4747f89ad239cd97f0c53ef4d3",
              "width": 64
            }
          ],
          "name": "Out of the Blue",
          "release_date": "1977",
          "release_date_precision": "year",
          "total_tracks": 17,
          "type": "album",
          "uri": "spotify:album:3usnShwygMXVZB4IV5dwnU"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7jefIIksOi1EazgRTfW2Pk"
            },
            "href": "https://api.spotify.com/v1/artists/7jefIIksOi1EazgRTfW2Pk",
            "id": "7jefIIksOi1EazgRTfW2Pk",
            "name": "Electric Light Orchestra",
            "type": "artist",
            "uri": "spotify:artist:7jefIIksOi1EazgRTfW2Pk"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 233293,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM17800593"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7ccnwVhaD3ITUQ2x8EkilA"
        },
        "href": "https://api.spotify.com/v1/tracks/7ccnwVhaD3ITUQ2x8EkilA",
        "id": "7ccnwVhaD3ITUQ2x8EkilA",
        "is_local": false,
        "name": "Jungle",
        "popularity": 44,
        "preview_url": "https://p.scdn.co/mp3-preview/ca7f99c7111dc2b4ddd7022f2a52f539d2fedcd0?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 7,
        "type": "track",
        "uri": "spotify:track:7ccnwVhaD3ITUQ2x8EkilA"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2019-01-16T17:51:50Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1ThoqLcyIYvZn7iWbj8fsj"
              },
              "href": "https://api.spotify.com/v1/artists/1ThoqLcyIYvZn7iWbj8fsj",
              "id": "1ThoqLcyIYvZn7iWbj8fsj",
              "name": "Bill Withers",
              "type": "artist",
              "uri": "spotify:artist:1ThoqLcyIYvZn7iWbj8fsj"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/6N8uPmDqbgXD3ztkCCfxoo"
          },
          "href": "https://api.spotify.com/v1/albums/6N8uPmDqbgXD3ztkCCfxoo",
          "id": "6N8uPmDqbgXD3ztkCCfxoo",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/57d0488448c8f0401e4f804d733af4f3f7b3c9ed",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ba9ebe79a63e36a643bc35df0dcaec2034d6267a",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/9ee1d01e0238c66f625523a5b92e1b9013002beb",
              "width": 64
            }
          ],
          "name": "Just As I Am",
          "release_date": "1971",
          "release_date_precision": "year",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:6N8uPmDqbgXD3ztkCCfxoo"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1ThoqLcyIYvZn7iWbj8fsj"
            },
            "href": "https://api.spotify.com/v1/artists/1ThoqLcyIYvZn7iWbj8fsj",
            "id": "1ThoqLcyIYvZn7iWbj8fsj",
            "name": "Bill Withers",
            "type": "artist",
            "uri": "spotify:artist:1ThoqLcyIYvZn7iWbj8fsj"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 121080,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM10000373"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1qfDfZAvrkSAFrAR2FTQDv"
        },
        "href": "https://api.spotify.com/v1/tracks/1qfDfZAvrkSAFrAR2FTQDv",
        "id": "1qfDfZAvrkSAFrAR2FTQDv",
        "is_local": false,
        "name": "Grandma's Hands",
        "popularity": 60,
        "preview_url": "https://p.scdn.co/mp3-preview/e93b8b4a7d89ee8e3bd4d6c8517699d5312e7263?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:1qfDfZAvrkSAFrAR2FTQDv"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2019-01-21T19:29:10Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "single",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/13ubrt8QOOCPljQ2FL1Kca"
              },
              "href": "https://api.spotify.com/v1/artists/13ubrt8QOOCPljQ2FL1Kca",
              "id": "13ubrt8QOOCPljQ2FL1Kca",
              "name": "A$AP Rocky",
              "type": "artist",
              "uri": "spotify:artist:13ubrt8QOOCPljQ2FL1Kca"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/3AlyvIIMZyT5LjWFeK5LSl"
          },
          "href": "https://api.spotify.com/v1/albums/3AlyvIIMZyT5LjWFeK5LSl",
          "id": "3AlyvIIMZyT5LjWFeK5LSl",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/38b3161861c640e63f37226af54812111fe9429c",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/127189577b8efaffed883e60587035492b43d506",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/802fe00844c0aa1490a366386bbfd805b3b5c6a2",
              "width": 64
            }
          ],
          "name": "Sundress",
          "release_date": "2018-11-20",
          "release_date_precision": "day",
          "total_tracks": 1,
          "type": "album",
          "uri": "spotify:album:3AlyvIIMZyT5LjWFeK5LSl"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/13ubrt8QOOCPljQ2FL1Kca"
            },
            "href": "https://api.spotify.com/v1/artists/13ubrt8QOOCPljQ2FL1Kca",
            "id": "13ubrt8QOOCPljQ2FL1Kca",
            "name": "A$AP Rocky",
            "type": "artist",
            "uri": "spotify:artist:13ubrt8QOOCPljQ2FL1Kca"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 158205,
        "episode": false,
        "explicit": true,
        "external_ids": {
          "isrc": "USRC11803252"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2aPTvyE09vUCRwVvj0I8WK"
        },
        "href": "https://api.spotify.com/v1/tracks/2aPTvyE09vUCRwVvj0I8WK",
        "id": "2aPTvyE09vUCRwVvj0I8WK",
        "is_local": false,
        "name": "Sundress",
        "popularity": 77,
        "preview_url": "https://p.scdn.co/mp3-preview/1254b77a883cda33c9bc5ed21fbe59b720e42db9?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2aPTvyE09vUCRwVvj0I8WK"
      },
      "video_thumbnail": {
        "url": null
      }
    },
    {
      "added_at": "2019-01-21T23:36:06Z",
      "added_by": {
        "external_urls": {
          "spotify": "https://open.spotify.com/user/hobogoh"
        },
        "href": "https://api.spotify.com/v1/users/hobogoh",
        "id": "hobogoh",
        "type": "user",
        "uri": "spotify:user:hobogoh"
      },
      "is_local": false,
      "primary_color": null,
      "track": {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5QdyldG4Fl4TPiOIeMNpBZ"
              },
              "href": "https://api.spotify.com/v1/artists/5QdyldG4Fl4TPiOIeMNpBZ",
              "id": "5QdyldG4Fl4TPiOIeMNpBZ",
              "name": "Big Thief",
              "type": "artist",
              "uri": "spotify:artist:5QdyldG4Fl4TPiOIeMNpBZ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/4onPyHor2yOlVxCsIaGyHH"
          },
          "href": "https://api.spotify.com/v1/albums/4onPyHor2yOlVxCsIaGyHH",
          "id": "4onPyHor2yOlVxCsIaGyHH",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/cefe04c64729c0af7b5064aadf173f4789cb4065",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/4e2bd65084afe1d0e456893f4141b05ac6ed7410",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/cff87cafba71f22c2171ca7da06c2e1ea8a946c1",
              "width": 64
            }
          ],
          "name": "Masterpiece",
          "release_date": "2016-05-27",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:4onPyHor2yOlVxCsIaGyHH"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/5QdyldG4Fl4TPiOIeMNpBZ"
            },
            "href": "https://api.spotify.com/v1/artists/5QdyldG4Fl4TPiOIeMNpBZ",
            "id": "5QdyldG4Fl4TPiOIeMNpBZ",
            "name": "Big Thief",
            "type": "artist",
            "uri": "spotify:artist:5QdyldG4Fl4TPiOIeMNpBZ"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 183894,
        "episode": false,
        "explicit": false,
        "external_ids": {
          "isrc": "US2U61623307"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/1uP8UVMXcTJn28TbhfR2Wo"
        },
        "href": "https://api.spotify.com/v1/tracks/1uP8UVMXcTJn28TbhfR2Wo",
        "id": "1uP8UVMXcTJn28TbhfR2Wo",
        "is_local": false,
        "name": "Paul",
        "popularity": 61,
        "preview_url": "https://p.scdn.co/mp3-preview/58baf0d20ffdc12951b644b00fabf760cac7350c?cid=774b29d4f13844c495f206cafdad9c86",
        "track": true,
        "track_number": 7,
        "type": "track",
        "uri": "spotify:track:1uP8UVMXcTJn28TbhfR2Wo"
      },
      "video_thumbnail": {
        "url": null
      }
    }
  ],
  "limit": 100,
  "next": null,
  "offset": 0,
  "previous": null,
  "total": 12
};
export {response};
