# Generated by Django 2.1.5 on 2019-01-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brains.Parties')),
            ],
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brains.Users'),
        ),
    ]
